language: minimal

env:
  - VERSION=4.9

install:
  - ./create-patch.sh "${VERSION}" travis-test.diff
  - git remote add upstream git://git.suckless.org/dmenu
  - git fetch --all

before_script:
  - cmp travis-test.diff "patch-${VERSION}.diff" || true
  - cat travis-test.diff || true
  - git branch -a --merged || true

script:
  - |
    cmp --silent travis-test.diff "patch-${VERSION}.diff" || \
      { echo "Patch is not up to date!" && exit 1 }
  - |
    git branch -a --merged | grep remotes/upstream/master > /dev/null 2>&1 || \
      { echo "New commits in upstream!" && exit 1 }
