name: Build
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 4.9
      filename: actions-test.diff

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Create patch
        run: ./create-patch.sh ${{env.version}} ${{env.filename}}

      - name: Check patch
        run: cmp --silent ${{env.filename}} patch-${{env.version}}.diff

      - name: Repository Dispatch to home-manager-configurations
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Gerschtli/home-manager-configurations
          event-type: update-dmenu
          client-payload: '{"commit_id": "${{ github.sha }}"}'
