name: Check upstream
on:
  schedule:
    - cron: 0 0 * * 1

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check upstream
        run: |
          git remote add upstream git://git.suckless.org/dmenu
          git fetch --all
          git branch -a --merged | grep remotes/upstream/master > /dev/null 2>&1
